import test from "node:test";
import assert from "node:assert/strict";
import { compareAgainstCorpus } from "../lib/plagiarism-detector";
import { atlasVectorPipeline, semanticCandidates } from "../lib/integrity-vector-search";

test("detects copied academic passage with source attribution",()=>{const copied="Public administration depends on transparent institutions and accountable public officials who can be evaluated by citizens.";const r=compareAgainstCorpus(`Introduction. ${copied} This study examines governance outcomes in local institutions.`,[{id:"a",title:"Governance Study",text:`Background material. ${copied} Further discussion follows.`}]);assert.ok(r.overallSimilarity>0);assert.ok(r.matches.some(m=>m.sourceTitle==="Governance Study"&&m.kind==="verbatim"));assert.ok(r.sourceSummaries[0].similarity>0)});
test("excludes bibliography from assessed similarity",()=>{const r=compareAgainstCorpus("This original discussion contains enough words to form an academic sentence about governance and development.\nReferences\nSmith, J. (2024). Governance and development in public institutions.",[{id:"r",title:"Reference",text:"Smith, J. (2024). Governance and development in public institutions."}]);assert.ok(r.excludedBibliographyWords>0);assert.equal(r.matches.length,0)});
test("does not invent matches when corpus is unrelated",()=>{const r=compareAgainstCorpus("Agricultural extension services can improve adoption when farmers receive timely locally relevant information and practical demonstrations.",[{id:"x",title:"Physics",text:"Quantum fields describe particles through excitations and mathematical operators in relativistic physical systems."}]);assert.equal(r.overallSimilarity,0);assert.equal(r.matches.length,0);assert.equal(r.risk,"low")});
test("reports lexical and semantic signals",()=>{const r=compareAgainstCorpus("Effective public institutions require accountable officials, transparent decision processes, and meaningful citizen oversight for sustainable governance outcomes.",[{id:"g",title:"Public Governance",text:"Sustainable governance outcomes require transparent decision processes, accountable public officials and meaningful oversight by citizens."}]);assert.ok(r.matches.length>0);assert.ok(r.matches[0].lexicalScore>=0);assert.ok(r.matches[0].semanticScore>0)});
test("separates contributions from multiple sources",()=>{const r=compareAgainstCorpus("Transparent budgeting enables citizens to monitor public expenditure and demand accountability. Agricultural extension improves farm decisions by delivering timely practical information to producers.",[{id:"1",title:"Budgeting",text:"Transparent budgeting enables citizens to monitor public expenditure and demand accountability."},{id:"2",title:"Extension",text:"Agricultural extension improves farm decisions by delivering timely practical information to producers."}]);assert.equal(r.sourceSummaries.length,2);assert.ok(r.overallSimilarity>50)});
test("builds an institution-filtered Atlas vector pipeline",()=>{const pipeline=atlasVectorPipeline([0.1,0.2,0.3],{limit:7,institution:"UNN"}) as Array<Record<string,any>>;assert.equal(pipeline[0].$vectorSearch.limit,7);assert.deepEqual(pipeline[0].$vectorSearch.filter,{institution:"UNN"});assert.equal(pipeline[0].$vectorSearch.path,"embedding")});
test("semantic candidates validate embedding dimensions and pass vector to corpus",async()=>{let seen:number[]=[];const results=await semanticCandidates("governance transparency",{model:"test",dimensions:3,async embed(){return [[0.2,0.4,0.6]]}},{async search(vector){seen=vector;return [{id:"1",title:"Match",text:"Evidence",score:0.9}]}},{limit:5});assert.deepEqual(seen,[0.2,0.4,0.6]);assert.equal(results[0].title,"Match")});
