"use client";

import { useEffect, useState } from "react";
import { RESEARCH_WORKSPACE_STORAGE_KEY, normalizeResearchWorkspace } from "@/lib/research-workspace";

type SourceSummary={sourceId:string;sourceTitle:string;sourceUrl?:string;matchedWords:number;similarityContribution:number;passageCount:number};
type Match={sourceTitle:string;sourceUrl?:string;submittedText:string;sourceText:string;score:number;lexicalScore:number;semanticScore:number;kind:string};
type Report={overallSimilarity:number;riskBand:string;matchedWords:number;totalWords:number;excludedQuotedWords:number;excludedBibliographyWords:number;sources:SourceSummary[];matches:Match[];methodology:string[];limitations:string[];scanId?:string|null;institutionalSources?:number;retainedInCorpus?:boolean;persistenceAvailable?:boolean};
type Discovered={id:string;title:string;year?:number;url?:string;doi?:string;text?:string;provider:string};
type SemanticCandidate={id:string;title:string;text:string;url?:string;score:number};
type SemanticStatus={configured:boolean;model:string|null;dimensions:number|null;index?:string};
function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]||c))}

export default function PlagiarismCheckerPage(){
 const[text,setText]=useState("");const[sources,setSources]=useState("");const[report,setReport]=useState<Report|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState(false);const[discovering,setDiscovering]=useState(false);const[semanticBusy,setSemanticBusy]=useState(false);const[fileName,setFileName]=useState("");const[query,setQuery]=useState("");const[discovered,setDiscovered]=useState<Discovered[]>([]);const[semantic,setSemantic]=useState<SemanticCandidate[]>([]);const[semanticStatus,setSemanticStatus]=useState<SemanticStatus|null>(null);const[institution,setInstitution]=useState("");const[useCorpus,setUseCorpus]=useState(true);const[retain,setRetain]=useState(false);
 useEffect(()=>{try{const raw=window.localStorage.getItem(RESEARCH_WORKSPACE_STORAGE_KEY);if(raw){const w=normalizeResearchWorkspace(JSON.parse(raw));setInstitution(w.institution);setQuery(w.title||w.keywords)}}catch{}void fetch("/api/plagiarism-check/semantic").then(r=>r.json()).then(setSemanticStatus).catch(()=>{})},[]);
 async function upload(file:File){setUploading(true);setError("");try{const form=new FormData();form.set("file",file);const res=await fetch("/api/plagiarism-check/extract",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||"Upload failed");setText(data.text);setFileName(data.fileName||file.name);if(data.warning)setError(data.warning)}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false)}}
 async function discover(){setDiscovering(true);setError("");try{const q=query.trim()||text.slice(0,700);const res=await fetch(`/api/plagiarism-check/discover?q=${encodeURIComponent(q)}`);const data=await res.json();if(!res.ok)throw new Error(data.error||"Discovery failed");setDiscovered(data.results||data.sources||[])}catch(e){setError(e instanceof Error?e.message:"Discovery failed")}finally{setDiscovering(false)}}
 function addDiscovered(){const usable=discovered.filter(x=>x.text&&x.text.length>=50);if(!usable.length){setError("The discovered records currently contain metadata only. Add full permitted source text before using them as similarity evidence.");return}const blocks=usable.map(x=>`TITLE: ${x.title}\n${x.text}`).join("\n---SOURCE---\n");setSources(prev=>prev.trim()?`${prev.trim()}\n---SOURCE---\n${blocks}`:blocks);setError("")}
 async function findSemantic(){setSemanticBusy(true);setError("");setSemantic([]);try{const res=await fetch("/api/plagiarism-check/semantic",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,institution,limit:20})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Semantic retrieval failed");setSemantic(data.candidates||[]);const blocks=(data.candidates||[]).filter((x:SemanticCandidate)=>x.text.length>=50).map((x:SemanticCandidate)=>`TITLE: ${x.title}\n${x.text}`).join("\n---SOURCE---\n");if(blocks)setSources(prev=>prev.trim()?`${prev.trim()}\n---SOURCE---\n${blocks}`:blocks)}catch(e){setError(e instanceof Error?e.message:"Semantic retrieval failed")}finally{setSemanticBusy(false)}}
 async function run(){setBusy(true);setError("");setReport(null);try{const parsed=sources.split(/\n---SOURCE---\n/i).map((block,i)=>{const lines=block.trim().split("\n");return{id:String(i+1),title:(lines.shift()||`Reference ${i+1}`).replace(/^TITLE:\s*/i,""),text:lines.join("\n")}}).filter(s=>s.text.length>=50);const res=await fetch("/api/plagiarism-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,fileName,sources:parsed,institution,useInstitutionalCorpus:useCorpus,retainInCorpus:retain})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Check failed");setReport(data)}catch(e){setError(e instanceof Error?e.message:"Check failed")}finally{setBusy(false)}}
 function downloadReport(){if(!report)return;const rows=report.sources.map(s=>`<tr><td>${escapeHtml(s.sourceTitle)}</td><td>${s.similarityContribution}%</td><td>${s.matchedWords}</td><td>${s.passageCount}</td></tr>`).join("");const matches=report.matches.slice(0,150).map(m=>`<section><h3>${m.score}% · ${escapeHtml(m.kind)} · ${escapeHtml(m.sourceTitle)}</h3><p>Lexical ${m.lexicalScore}% · semantic proxy ${m.semanticScore}%</p><p><b>Submission:</b> ${escapeHtml(m.submittedText)}</p><p><b>Source:</b> ${escapeHtml(m.sourceText)}</p></section>`).join("");const html=`<!doctype html><html><head><meta charset="utf-8"><title>Scholar Similarity Report</title><style>body{font-family:Arial,sans-serif;max-width:900px;margin:40px auto;line-height:1.5}table{width:100%;border-collapse:collapse}td,th{border:1px solid #bbb;padding:8px;text-align:left}section{border-top:1px solid #ccc;padding:12px 0}@media print{button{display:none}}</style></head><body><h1>Scholar Integrity Engine Similarity Report</h1><p><b>Document:</b> ${escapeHtml(fileName||"Pasted submission")}</p><p><b>Overall similarity:</b> ${report.overallSimilarity}% · ${escapeHtml(report.riskBand)}</p><p>${report.matchedWords} of ${report.totalWords} assessed words occur in evidence-backed matched passages.</p><p><b>Report ID:</b> ${escapeHtml(report.scanId||"not persisted")}</p><h2>Source overview</h2><table><thead><tr><th>Source</th><th>Contribution</th><th>Matched words</th><th>Passages</th></tr></thead><tbody>${rows}</tbody></table><h2>Matched passages</h2>${matches}<h2>Interpretation</h2><p>Similarity is evidence for human review, not by itself proof of plagiarism or academic misconduct. Scholar is independent and does not access Turnitin's proprietary corpus.</p><button onclick="window.print()">Print / Save PDF</button></body></html>`;const blob=new Blob([html],{type:"text/html"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`scholar-similarity-report-${report.scanId||Date.now()}.html`;a.click();URL.revokeObjectURL(url)}
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px"}}><h1>Scholar Integrity Engine</h1><p>Evidence-backed similarity screening for theses, projects, assignments and articles. Detect verbatim, near-verbatim and paraphrase-like overlap and inspect source evidence before making an academic-integrity judgment.</p><div style={{padding:14,border:"1px solid #ddd",borderRadius:12,margin:"18px 0"}}><strong>Independent system:</strong> Scholar is not Turnitin and does not access Turnitin&apos;s proprietary corpus. {semanticStatus?.configured?`Real embedding retrieval is configured with ${semanticStatus.model} (${semanticStatus.dimensions} dimensions).`:"Lexical and semantic-proxy checking works without an embedding API; real vector retrieval activates when the embedding provider and Atlas index are configured."}</div>
 <h2>1. Upload or paste submission</h2><input type="file" accept=".txt,.md,.docx,.pdf,text/plain,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}} disabled={uploading}/>{uploading&&<span> Extracting document…</span>}{fileName&&<p><strong>Loaded:</strong> {fileName}</p>}<textarea value={text} onChange={e=>setText(e.target.value)} rows={14} style={{width:"100%",margin:"10px 0 18px",padding:12}} placeholder="Upload DOCX/PDF/TXT or paste the document here…"/>
 <h2>2. Discover and retrieve evidence</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={query} onChange={e=>setQuery(e.target.value)} style={{flex:"1 1 500px",padding:10}} placeholder="Topic, title or distinctive passage…"/><button onClick={discover} disabled={discovering}>{discovering?"Searching…":"Search OpenAlex + Crossref"}</button>{discovered.length>0&&<button onClick={addDiscovered}>Add usable evidence</button>}<button onClick={findSemantic} disabled={semanticBusy||!semanticStatus?.configured||text.length<40}>{semanticBusy?"Retrieving…":"Find semantic corpus matches"}</button></div>{discovered.length>0&&<p>{discovered.length} academic records found; {discovered.filter(x=>x.text&&x.text.length>=50).length} include enough abstract text for direct evidence matching.</p>}{semantic.length>0&&<p>{semantic.length} embedding-based corpus candidates added for passage-level verification.</p>}
 <h2>3. Comparison corpus</h2><label style={{display:"block",marginBottom:8}}>Institution <input value={institution} onChange={e=>setInstitution(e.target.value)} style={{padding:8,minWidth:300,marginLeft:8}} placeholder="Optional institution filter"/></label><label style={{display:"block",margin:"8px 0"}}><input type="checkbox" checked={useCorpus} onChange={e=>setUseCorpus(e.target.checked)}/> Compare against Scholar&apos;s permissioned institutional corpus.</label><textarea value={sources} onChange={e=>setSources(e.target.value)} rows={10} style={{width:"100%",margin:"8px 0 12px",padding:12}} placeholder={'TITLE: Source one\nSource text…\n---SOURCE---\nTITLE: Source two\nSource text…'}/><label style={{display:"block",padding:12,border:"1px solid #ddd",borderRadius:8,margin:"10px 0"}}><input type="checkbox" checked={retain} onChange={e=>setRetain(e.target.checked)}/> <strong>Optional corpus contribution:</strong> retain this submission for future self-plagiarism and institutional similarity comparisons.</label><button onClick={run} disabled={busy||uploading} style={{padding:"12px 20px",fontWeight:700}}>{busy?"Running integrity analysis…":"Run Integrity Check"}</button>{error&&<p style={{fontWeight:700}}>{error}</p>}
 {report&&<section style={{marginTop:30}}><h2>Similarity: {report.overallSimilarity}% · {report.riskBand}</h2><p>{report.matchedWords.toLocaleString()} of {report.totalWords.toLocaleString()} assessed words occur in evidence-backed matched passages. Excluded: {report.excludedQuotedWords} quoted words and {report.excludedBibliographyWords} bibliography words.</p><p><strong>Institutional sources loaded:</strong> {report.institutionalSources||0} · <strong>Scan history:</strong> {report.scanId?`saved as ${report.scanId}`:"not saved"} · <strong>Corpus retention:</strong> {report.retainedInCorpus?"yes, with your opt-in":"no"}</p><button onClick={downloadReport} style={{padding:"10px 16px",fontWeight:700}}>Download similarity report (HTML / print to PDF)</button><h3>Source overview</h3>{report.sources.length===0?<p>No matched sources.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Source</th><th>Contribution</th><th>Matched words</th><th>Passages</th></tr></thead><tbody>{report.sources.map(s=><tr key={s.sourceId}><td>{s.sourceTitle}</td><td align="center">{s.similarityContribution}%</td><td align="center">{s.matchedWords}</td><td align="center">{s.passageCount}</td></tr>)}</tbody></table></div>}<h3>Matched passages</h3>{report.matches.length===0?<p>No evidence-backed matches were found in the available corpus.</p>:report.matches.slice(0,150).map((m,i)=><article key={i} style={{padding:14,border:"1px solid #ddd",borderRadius:10,margin:"10px 0"}}><strong>{m.score}% · {m.kind} · {m.sourceTitle}</strong><p style={{fontSize:13}}>Lexical {m.lexicalScore}% · semantic proxy {m.semanticScore}%</p><p><b>Submission:</b> {m.submittedText}</p><p><b>Source:</b> {m.sourceText}</p>{m.sourceUrl&&<p><a href={m.sourceUrl} target="_blank" rel="noreferrer">Open evidence source</a></p>}</article>)}<h3>Method</h3><ul>{report.methodology.map(x=><li key={x}>{x}</li>)}</ul><h3>Interpretation limits</h3><ul>{report.limitations.map(x=><li key={x}>{x}</li>)}</ul></section>}</main>
}
