"use client";
import { useState } from "react";
type Match={sourceTitle:string;sourceUrl?:string;submittedText:string;sourceText:string;score:number;lexicalScore:number;semanticScore:number;kind:string};
type Report={overallSimilarity:number;matchedWords:number;totalWords:number;risk:string;excludedQuotedWords:number;excludedBibliographyWords:number;sourceSummaries:Array<{sourceId:string;sourceTitle:string;sourceUrl?:string;similarity:number;matchedWords:number;matches:number}>;matches:Match[];methodology:string[];limitations:string[]};
export default function PlagiarismCheckerPage(){const[text,setText]=useState("");const[sources,setSources]=useState("");const[report,setReport]=useState<Report|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
async function run(){setBusy(true);setError("");setReport(null);try{const parsed=sources.split(/\n---SOURCE---\n/i).map((block,i)=>{const lines=block.trim().split("\n");return{id:String(i+1),title:(lines.shift()||`Reference ${i+1}`).replace(/^TITLE:\s*/i,""),text:lines.join("\n")}}).filter(s=>s.text.length>=50);const res=await fetch("/api/plagiarism-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,sources:parsed})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Check failed");setReport(data)}catch(e){setError(e instanceof Error?e.message:"Check failed")}finally{setBusy(false)}}
return <main style={{maxWidth:1100,margin:"0 auto",padding:"32px 20px"}}><h1>Scholar Integrity Engine</h1><p>Multi-layer academic similarity screening for verbatim, near-verbatim and paraphrased passages, with evidence and source attribution.</p><div style={{padding:14,border:"1px solid #ddd",borderRadius:12,margin:"18px 0"}}><strong>Independent checker:</strong> Scholar does not access Turnitin&apos;s proprietary database. Results reflect the corpus supplied or indexed in Scholar and should support human academic-integrity review.</div>
<label><strong>Document to check</strong></label><textarea value={text} onChange={e=>setText(e.target.value)} rows={14} style={{width:"100%",margin:"8px 0 18px",padding:12}} placeholder="Paste thesis, assignment, dissertation or article text…"/><label><strong>Reference corpus</strong></label><p style={{fontSize:14}}>Use TITLE: on the first line, then source text. Separate sources with <code>---SOURCE---</code>.</p><textarea value={sources} onChange={e=>setSources(e.target.value)} rows={12} style={{width:"100%",margin:"8px 0 18px",padding:12}} placeholder={'TITLE: Source one\nSource text…\n---SOURCE---\nTITLE: Source two\nSource text…'}/><button onClick={run} disabled={busy} style={{padding:"12px 20px",fontWeight:700}}>{busy?"Analyzing…":"Check Similarity"}</button>{error&&<p style={{fontWeight:700}}>{error}</p>}
{report&&<section style={{marginTop:30}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><div style={{padding:18,border:"1px solid #ddd",borderRadius:12}}><small>OVERALL SIMILARITY</small><h2>{report.overallSimilarity}%</h2></div><div style={{padding:18,border:"1px solid #ddd",borderRadius:12}}><small>REVIEW BAND</small><h2>{report.risk.replace("-"," ").toUpperCase()}</h2></div><div style={{padding:18,border:"1px solid #ddd",borderRadius:12}}><small>MATCHED WORDS</small><h2>{report.matchedWords.toLocaleString()}</h2></div></div><p>{report.totalWords.toLocaleString()} words assessed. Excluded {report.excludedQuotedWords} quoted and {report.excludedBibliographyWords} bibliography words.</p>
<h3>Sources</h3>{report.sourceSummaries.length===0?<p>No evidence-backed source matches.</p>:report.sourceSummaries.map(s=><div key={s.sourceId} style={{padding:12,borderBottom:"1px solid #ddd"}}><strong>{s.similarity}% — {s.sourceTitle}</strong><div>{s.matchedWords} matched words · {s.matches} passage{s.matches===1?"":"s"}</div></div>)}
<h3>Matched passages</h3>{report.matches.slice(0,100).map((m,i)=><article key={i} style={{padding:14,border:"1px solid #ddd",borderRadius:10,margin:"10px 0"}}><strong>{m.score}% hybrid · {m.kind} · {m.sourceTitle}</strong><div style={{fontSize:13,marginTop:4}}>Lexical {m.lexicalScore}% · Semantic proxy {m.semanticScore}%</div><p><b>Submission:</b> {m.submittedText}</p><p><b>Source:</b> {m.sourceText}</p></article>)}<h3>Method</h3><ul>{report.methodology.map(x=><li key={x}>{x}</li>)}</ul><h3>Interpretation limits</h3><ul>{report.limitations.map(x=><li key={x}>{x}</li>)}</ul></section>}</main>}
