"use client";

import { useState } from "react";

type SourceSummary={sourceId:string;sourceTitle:string;sourceUrl?:string;matchedWords:number;similarityContribution:number;passageCount:number};
type Report={overallSimilarity:number;riskBand:string;matchedWords:number;totalWords:number;excludedQuotedWords:number;excludedBibliographyWords:number;sources:SourceSummary[];matches:Array<{sourceTitle:string;sourceUrl?:string;submittedText:string;sourceText:string;score:number;lexicalScore:number;semanticScore:number;kind:string}>;methodology:string[];limitations:string[]};
type Discovered={id:string;title:string;authors:string;year?:number;url?:string;text?:string;provider:string};

export default function PlagiarismCheckerPage(){
 const[text,setText]=useState("");const[sources,setSources]=useState("");const[report,setReport]=useState<Report|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[uploading,setUploading]=useState(false);const[discovering,setDiscovering]=useState(false);const[fileName,setFileName]=useState("");const[query,setQuery]=useState("");const[discovered,setDiscovered]=useState<Discovered[]>([]);
 async function upload(file:File){setUploading(true);setError("");try{const form=new FormData();form.set("file",file);const res=await fetch("/api/plagiarism-check/extract",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||"Upload failed");setText(data.text);setFileName(data.fileName||file.name);if(data.warning)setError(data.warning)}catch(e){setError(e instanceof Error?e.message:"Upload failed")}finally{setUploading(false)}}
 async function discover(){setDiscovering(true);setError("");try{const q=query.trim()||text.slice(0,700);const res=await fetch(`/api/plagiarism-check/discover?q=${encodeURIComponent(q)}`);const data=await res.json();if(!res.ok)throw new Error(data.error||"Discovery failed");setDiscovered(data.results||[])}catch(e){setError(e instanceof Error?e.message:"Discovery failed")}finally{setDiscovering(false)}}
 function addDiscovered(){const usable=discovered.filter(x=>x.text&&x.text.length>=50);if(!usable.length){setError("The discovered records currently contain metadata only. Add full permitted source text before using them as similarity evidence.");return}const blocks=usable.map(x=>`TITLE: ${x.title}\n${x.text}`).join("\n---SOURCE---\n");setSources(prev=>prev.trim()?`${prev.trim()}\n---SOURCE---\n${blocks}`:blocks)}
 async function run(){setBusy(true);setError("");setReport(null);try{const parsed=sources.split(/\n---SOURCE---\n/i).map((block,i)=>{const lines=block.trim().split("\n");return{id:String(i+1),title:(lines.shift()||`Reference ${i+1}`).replace(/^TITLE:\s*/i,""),text:lines.join("\n")}}).filter(s=>s.text.length>=50);const res=await fetch("/api/plagiarism-check",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text,sources:parsed})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Check failed");setReport(data)}catch(e){setError(e instanceof Error?e.message:"Check failed")}finally{setBusy(false)}}
 return <main style={{maxWidth:1120,margin:"0 auto",padding:"32px 20px"}}><h1>Scholar Integrity Engine</h1><p>Evidence-backed similarity screening for theses, projects, assignments and articles. Detect verbatim, near-verbatim and paraphrase-like overlap and inspect the source evidence before making an academic-integrity judgment.</p>
 <div style={{padding:14,border:"1px solid #ddd",borderRadius:12,margin:"18px 0"}}><strong>Independent system:</strong> Scholar is not Turnitin and does not access Turnitin&apos;s proprietary student-paper or publisher corpus. Scholar now includes the data model for a growing institutional corpus and scan history; semantic vector retrieval activates after an embedding provider and Atlas vector index are configured.</div>
 <h2>1. Upload or paste submission</h2><input type="file" accept=".txt,.md,.docx,.pdf,text/plain,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}} disabled={uploading}/>{uploading&&<span> Extracting document…</span>}{fileName&&<p><strong>Loaded:</strong> {fileName}</p>}<textarea value={text} onChange={e=>setText(e.target.value)} rows={14} style={{width:"100%",margin:"10px 0 18px",padding:12}} placeholder="Upload DOCX/PDF/TXT or paste the document here…"/>
 <h2>2. Discover academic sources</h2><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><input value={query} onChange={e=>setQuery(e.target.value)} style={{flex:"1 1 500px",padding:10}} placeholder="Topic, title or distinctive passage…"/><button onClick={discover} disabled={discovering}>{discovering?"Searching…":"Search OpenAlex + Crossref"}</button>{discovered.length>0&&<button onClick={addDiscovered}>Add usable evidence</button>}</div>{discovered.length>0&&<p>{discovered.length} academic records found; {discovered.filter(x=>x.text&&x.text.length>=50).length} currently include enough text for evidence matching.</p>}
 <h2>3. Reference / institutional corpus</h2><p style={{fontSize:14}}>Add theses, projects, previous submissions, articles or other permitted source text. Separate sources with <code>---SOURCE---</code>. The new persistence model is ready for MongoDB-backed corpus ingestion.</p><textarea value={sources} onChange={e=>setSources(e.target.value)} rows={12} style={{width:"100%",margin:"8px 0 18px",padding:12}} placeholder={'TITLE: Source one\nSource text…\n---SOURCE---\nTITLE: Source two\nSource text…'}/><button onClick={run} disabled={busy||uploading} style={{padding:"12px 20px",fontWeight:700}}>{busy?"Running integrity analysis…":"Run Integrity Check"}</button>{error&&<p style={{fontWeight:700}}>{error}</p>}
 {report&&<section style={{marginTop:30}}><h2>Similarity: {report.overallSimilarity}% · {report.riskBand}</h2><p>{report.matchedWords.toLocaleString()} of {report.totalWords.toLocaleString()} assessed words occur in evidence-backed matched passages. Excluded: {report.excludedQuotedWords} quoted words and {report.excludedBibliographyWords} bibliography words.</p><h3>Source overview</h3>{report.sources.length===0?<p>No matched sources.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">Source</th><th>Contribution</th><th>Matched words</th><th>Passages</th></tr></thead><tbody>{report.sources.map(s=><tr key={s.sourceId}><td>{s.sourceTitle}</td><td align="center">{s.similarityContribution}%</td><td align="center">{s.matchedWords}</td><td align="center">{s.passageCount}</td></tr>)}</tbody></table></div>}<h3>Matched passages</h3>{report.matches.length===0?<p>No evidence-backed matches were found in the supplied corpus.</p>:report.matches.slice(0,150).map((m,i)=><article key={i} style={{padding:14,border:"1px solid #ddd",borderRadius:10,margin:"10px 0"}}><strong>{m.score}% · {m.kind} · {m.sourceTitle}</strong><p style={{fontSize:13}}>Lexical {m.lexicalScore}% · semantic proxy {m.semanticScore}%</p><p><b>Submission:</b> {m.submittedText}</p><p><b>Source:</b> {m.sourceText}</p>{m.sourceUrl&&<p><a href={m.sourceUrl} target="_blank" rel="noreferrer">Open evidence source</a></p>}</article>)}<h3>Method</h3><ul>{report.methodology.map(x=><li key={x}>{x}</li>)}</ul><h3>Interpretation limits</h3><ul>{report.limitations.map(x=><li key={x}>{x}</li>)}</ul></section>}</main>
}
